# Generated by Django 3.2.4 on 2021-07-01 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='indexKey',
            new_name='index',
        ),
    ]
